### ISSUE TITLE
raspberry pi 3 b stock button

### ISSUE THREAD

**Issue by davibe** [bnielsen1965/rpi-gpio-buttons#6]
is it possible to detect the pressure of the button that is already present on the rpi board ?

**Comment by bnielsen1965** [comment]
Already pressed? Let me know if I misunderstood your question.

This would require a change to the code...

When rpi-gpio-buttons starts it [calls buttonSetup() on line 161](https://github.com/bnielsen1965/rpi-gpio-buttons/blob/master/index.js#L161) for each button pin you define.

In buttonSetup() it sets the initial button state to STATE_INIT and eventually reads the button pin asynchronously where it sets the initialized state to STATE_PRESSED if the button is already pressed or to STATE_IDLE if the button is not pressed.

A new method would be needed to read the button state because the *buttons* array is a private member in rpi-gpio-buttons. Or the buttonSetup() function could be modified to emit the initialized state once it is known, that might be a better solution since the read is asynchronous.

**Comment by bnielsen1965** [comment]
@davibe I'm not sure I understand your question but I just published a new version of rpi-gpio-buttons and when it initializes the GPIO pins it will do a preread of the button state in case the user is already pressing on the button when the button events start.
